# Generated by Django 5.1.3 on 2024-11-24 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contaComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroConta', models.IntegerField()),
                ('aberturaConta', models.DateField()),
                ('fechamentoConta', models.DateField(null=True)),
                ('situacaoConta', models.IntegerField()),
                ('senhaConta', models.CharField(max_length=30)),
                ('saldoConta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomePessoa', models.CharField(max_length=100)),
                ('enderecoPessoa', models.CharField(max_length=300)),
                ('cepPessoa', models.IntegerField()),
                ('telefonePessoa', models.CharField(max_length=100)),
                ('rendaPessoa', models.FloatField()),
                ('situacaoPessoa', models.IntegerField(default=1)),
                ('cpfPessoa', models.CharField(max_length=11, unique=True)),
                ('rgPessoa', models.CharField(max_length=10)),
                ('dataNascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoMovimento', models.IntegerField()),
                ('dataMovimento', models.DateTimeField()),
                ('horaMovimento', models.TimeField()),
                ('valorMovimento', models.FloatField()),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_bancario_app.contacomum')),
            ],
        ),
        migrations.AddField(
            model_name='contacomum',
            name='idCliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_bancario_app.pessoafisica'),
        ),
    ]
