# Generated by Django 5.1.3 on 2024-11-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_bancario_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movimento',
            old_name='conta',
            new_name='idConta',
        ),
        migrations.AlterField(
            model_name='contacomum',
            name='numeroConta',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='contacomum',
            name='saldoConta',
            field=models.IntegerField(default=0),
        ),
    ]
